// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TripPlanner.Infrastructure.Persistence;

#nullable disable

namespace TripPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514200811_RenamePlaceToTripPlace")]
    partial class RenamePlaceToTripPlace
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TripPlanner.Domain.Entities.PlaceDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlaceDetails");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.PlaceProviderEndpointCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EndpointType")
                        .HasColumnType("int");

                    b.Property<int>("PlaceProvider")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlaceProviderEndpointCosts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("24b519c7-3cd5-4e03-984f-97e4946e1b5d"),
                            Cost = 0.00283m,
                            CreatedAtUtc = new DateTime(2026, 5, 10, 10, 29, 50, 0, DateTimeKind.Utc),
                            EndpointType = 1,
                            PlaceProvider = 1
                        },
                        new
                        {
                            Id = new Guid("50511583-e3fd-4997-87c7-745cd25118d2"),
                            Cost = 0.0m,
                            CreatedAtUtc = new DateTime(2026, 5, 10, 10, 29, 50, 0, DateTimeKind.Utc),
                            EndpointType = 2,
                            PlaceProvider = 1
                        },
                        new
                        {
                            Id = new Guid("6d6656ed-616e-48c9-b990-f69fa10e58d6"),
                            Cost = 0.005m,
                            CreatedAtUtc = new DateTime(2026, 5, 10, 10, 29, 50, 0, DateTimeKind.Utc),
                            EndpointType = 3,
                            PlaceProvider = 1
                        },
                        new
                        {
                            Id = new Guid("734eed77-4170-440b-87a5-49cd0eba1232"),
                            Cost = 0.017m,
                            CreatedAtUtc = new DateTime(2026, 5, 10, 10, 29, 50, 0, DateTimeKind.Utc),
                            EndpointType = 4,
                            PlaceProvider = 1
                        },
                        new
                        {
                            Id = new Guid("80be5d69-4b9a-4325-bc25-98d5a4d1339b"),
                            Cost = 0.02m,
                            CreatedAtUtc = new DateTime(2026, 5, 10, 10, 29, 50, 0, DateTimeKind.Utc),
                            EndpointType = 5,
                            PlaceProvider = 1
                        },
                        new
                        {
                            Id = new Guid("90763803-9b7c-43ea-b2e6-2c1eec863f23"),
                            Cost = 0.007m,
                            CreatedAtUtc = new DateTime(2026, 5, 10, 10, 29, 50, 0, DateTimeKind.Utc),
                            EndpointType = 6,
                            PlaceProvider = 1
                        },
                        new
                        {
                            Id = new Guid("9c05f5f2-ad9f-4c23-9a5a-32d84d5bf7d6"),
                            Cost = 0.0m,
                            CreatedAtUtc = new DateTime(2026, 5, 10, 10, 29, 50, 0, DateTimeKind.Utc),
                            EndpointType = 7,
                            PlaceProvider = 1
                        },
                        new
                        {
                            Id = new Guid("9ff32d8d-ba07-4cff-abbc-b17a25449cb7"),
                            Cost = 0.032m,
                            CreatedAtUtc = new DateTime(2026, 5, 10, 10, 29, 50, 0, DateTimeKind.Utc),
                            EndpointType = 8,
                            PlaceProvider = 1
                        },
                        new
                        {
                            Id = new Guid("a399866c-d277-46cd-9808-0e84dd0589e5"),
                            Cost = 0.035m,
                            CreatedAtUtc = new DateTime(2026, 5, 10, 10, 29, 50, 0, DateTimeKind.Utc),
                            EndpointType = 9,
                            PlaceProvider = 1
                        },
                        new
                        {
                            Id = new Guid("b20f5d08-fff1-4a64-87d5-82ed2f54628b"),
                            Cost = 0.032m,
                            CreatedAtUtc = new DateTime(2026, 5, 10, 10, 29, 50, 0, DateTimeKind.Utc),
                            EndpointType = 10,
                            PlaceProvider = 1
                        },
                        new
                        {
                            Id = new Guid("c777bb6d-9f16-473b-8522-d7426b7d30dd"),
                            Cost = 0.035m,
                            CreatedAtUtc = new DateTime(2026, 5, 10, 10, 29, 50, 0, DateTimeKind.Utc),
                            EndpointType = 11,
                            PlaceProvider = 1
                        });
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.PlaceProviderRequestLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationMs")
                        .HasColumnType("int");

                    b.Property<int>("EndpointType")
                        .HasColumnType("int");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("PlaceProviderRequestLogs");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DestinationExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.TripPlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DayNumber")
                        .HasColumnType("int");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("PlaceDetailsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly?>("PlannedTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlaceDetailsId");

                    b.HasIndex("TripId");

                    b.ToTable("TripPlaces", (string)null);
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.TripShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Permission")
                        .HasColumnType("int");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TripId", "UserId")
                        .IsUnique();

                    b.ToTable("TripShares");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.Trip", b =>
                {
                    b.HasOne("TripPlanner.Domain.Entities.User", "User")
                        .WithMany("Trips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.TripPlace", b =>
                {
                    b.HasOne("TripPlanner.Domain.Entities.PlaceDetails", "PlaceDetails")
                        .WithMany()
                        .HasForeignKey("PlaceDetailsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TripPlanner.Domain.Entities.Trip", "Trip")
                        .WithMany("Places")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaceDetails");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.TripShare", b =>
                {
                    b.HasOne("TripPlanner.Domain.Entities.Trip", "Trip")
                        .WithMany("TripShares")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripPlanner.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.Trip", b =>
                {
                    b.Navigation("Places");

                    b.Navigation("TripShares");
                });

            modelBuilder.Entity("TripPlanner.Domain.Entities.User", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
